export class MappingDTO {
    constructor(
    //    public  gap_in_days: string,
    //    public filter_with_grid: string,
    //    public  filter_with_flags: string,
    //    public  check_ranges: string,
    //    public  make_health_charts: string,
    //    public  make_data_charts: string,
    //    public  baseload: string,
    //    public  primary_reserve: string,
    //    public  detect_parameters: string,
    //    public  data_time_interval_se: string,
    //    public  use_price_data_$_MWh: string,
    //    public  alternative_fixed_price: string,
    //    public  reserve_MW_price: string,
    //    public  auto_size_bat: string,
    //    public  battery_power_MW: string,
    //    public  battery_energy_MWH: string,
    //    public  gas_price_mwh: string,
    //    public  gas_LHV: string,
    //    public  battery_eff: string,
    //    public  limit_PFRLDCMD_signal: string, 
    //    public  search_metadata: string,
    //    public  osm_or_ext_data: string,
    //    public  rename_output: string,
    //    public  batt_percent_to_pr: string,
    //    public  batt_power_limit_to_pr: string,
    //    public  batt_for_black_start: string,
    //    public  batt_price_MWh: string,
    //    public  batt_price_MW: string,
    //    public  converter_price_MVA: string,
    //    public  export_results_tocsv: string
      //  public  name: string,
    //    public  description: string,
       public st1_power: string,
       public gt1_ambient_temp: string,
       public gt1_power: string,
       public gt1_fuel_flow: string,
       public gt1_grid_connected: string,
       public gt1_primary_responce: string,
       public gt1_frequency: string,
       public gt2_ambient_temp: string,
       public gt2_power: string,
       public gt2_fuel_flow: string,
       public gt2_grid_connected: string,
       public gt2_primary_responce: string,
       public gt2_frequency: string,
       public gt3_ambient_temp: string,
       public gt3_power: string,
       public gt3_fuel_flow: string,
       public gt3_grid_connected: string,
       public gt3_primary_responce: string,
       public gt3_frequency: string,

    ) {}
  }
