version: '3'

networks:
  crm-central:

services:
  db:
    image: mysql:8.0.20
    hostname: crm-central-db
    container_name: crm-central-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${PORT_DB}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - crm-central

  db_admin:
    image: phpmyadmin/phpmyadmin
    hostname: crm-central-db-admin
    container_name: crm-central-db-admin
    restart: always
    ports:
      - "${PORT_DB_ADMIN}:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - crm-central

